;; BHV_PARAM0=1000 		-- BHVPARAM_SCANTIME(主动怪)
;; BHV_PARAM1=15000		-- BHVPARAM_RANDMOVETIME（可以移动）
;; BHV_PARAM2=0				-- BHVPARAM_CANNOTATTACK（能否攻击）
;; BHV_PARAM3=35000		-- BHVPARAM_RETURN（回家距离）
;; BHV_PARAM4=5000		-- BHVPARAM_SCANENEMYDIST（扫敌距离）
;; BHV_PARAM5=8000		-- BHVPARAM_SCANTEAMMATEDIST（扫友距离）
;; BHV_PARAM6=2000 		-- BHVPARAM_RESETTARGET_DIST
;; BHV_PARAM7=1 			-- BHVPARAM_RET_ORI_STATE
;; BHV_PARAM8=1				-- BHVPARAM_STRIKEBACK（还击怪）

[INFO]
BHVCOUNT=32

[BHV0]
DESC=主动攻击，会随机移动，可以攻击（巡逻），会还击
BHV_PARAM0=1000 ;!!!-1非主动攻击， 其他数值无效，即扫描敌人的时间不可以进行配置
BHV_PARAM1=15000		;随机移动的时间间隔，如果是-1，则不会随机移动
BHV_PARAM2=0		;不能被攻击（无敌）
BHV_PARAM3=35000		;离开出生地的距离大于此值时，放弃追赶敌人
BHV_PARAM4=5000		;扫描敌人的最大距离
BHV_PARAM5=8000		;扫描队友的最大距离
BHV_PARAM6=2000 ;!!!该项配置已经失效如果当前的移动目标和敌人的位置之间的距离大于此数值,则需要重新设定移动目标
BHV_PARAM7=1 		;是否可以回到原始状态，比如回血，清除buff
BHV_PARAM8=1		;是否会还击

[BHV1]
DESC=不主动攻击，会随机移动，可以攻击，会还击
BHV_PARAM0=-1		;!!!-1非主动攻击， 其他数值无效，即扫描敌人的时间不可以进行配置
BHV_PARAM1=12000		;随机移动的时间间隔，如果是-1，则不会随机移动
BHV_PARAM2=0		;不能被攻击（无敌）
BHV_PARAM3=35000		;离开出生地的距离大于此值时，放弃追赶敌人
BHV_PARAM4=5000		;扫描敌人的最大距离
BHV_PARAM5=8000		;扫描队友的最大距离
BHV_PARAM6=2000 ;!!!该项配置已经失效如果当前的移动目标和敌人的位置之间的距离大于此数值,则需要重新设定移动目标
BHV_PARAM7=1 		;是否可以回到原始状态，比如回血，清除buff
BHV_PARAM8=1		;是否会还击

[BHV2]
DESC=不主动攻击，会随机移动，不可以攻击，不会还击
BHV_PARAM0=-1		;!!!-1非主动攻击， 其他数值无效，即扫描敌人的时间不可以进行配置
BHV_PARAM1=18000		;随机移动的时间间隔，如果是-1，则不会随机移动
BHV_PARAM2=1		;不能被攻击（无敌）
BHV_PARAM3=35000		;离开出生地的距离大于此值时，放弃追赶敌人
BHV_PARAM4=5000		;扫描敌人的最大距离
BHV_PARAM5=8000		;扫描队友的最大距离
BHV_PARAM6=2000 ;!!!该项配置已经失效如果当前的移动目标和敌人的位置之间的距离大于此数值,则需要重新设定移动目标
BHV_PARAM7=1 		;是否可以回到原始状态，比如回血，清除buff
BHV_PARAM8=0		;是否会还击

[BHV3]
DESC=不主动攻击，不随机移动，不可以攻击，不会还击
BHV_PARAM0=-1		;!!!-1非主动攻击， 其他数值无效，即扫描敌人的时间不可以进行配置
BHV_PARAM1=-1		;随机移动的时间间隔，如果是-1，则不会随机移动
BHV_PARAM2=1		;不能被攻击（无敌）
BHV_PARAM3=35000		;离开出生地的距离大于此值时，放弃追赶敌人
BHV_PARAM4=5000		;扫描敌人的最大距离
BHV_PARAM5=8000		;扫描队友的最大距离
BHV_PARAM6=2000 ;!!!该项配置已经失效如果当前的移动目标和敌人的位置之间的距离大于此数值,则需要重新设定移动目标
BHV_PARAM7=1 		;是否可以回到原始状态，比如回血，清除buff
BHV_PARAM8=0		;是否会还击

[BHV4]
DESC=主动攻击，会随机移动，可以攻击，会还击（不巡逻）
BHV_PARAM0=1000 ;!!!-1非主动攻击， 其他数值无效，即扫描敌人的时间不可以进行配置
BHV_PARAM1=10000		;随机移动的时间间隔，如果是-1，则不会随机移动
BHV_PARAM2=0		;不能被攻击（无敌）
BHV_PARAM3=35000		;离开出生地的距离大于此值时，放弃追赶敌人
BHV_PARAM4=5000		;扫描敌人的最大距离
BHV_PARAM5=8000		;扫描队友的最大距离
BHV_PARAM6=2000 ;!!!该项配置已经失效如果当前的移动目标和敌人的位置之间的距离大于此数值,则需要重新设定移动目标
BHV_PARAM7=1 		;是否可以回到原始状态，比如回血，清除buff
BHV_PARAM8=1		;是否会还击

[BHV5]
DESC=主动攻击，不会随机移动，可以攻击，会还击
BHV_PARAM0=1000 ;!!!-1非主动攻击， 其他数值无效，即扫描敌人的时间不可以进行配置
BHV_PARAM1=-1		;随机移动的时间间隔，如果是-1，则不会随机移动
BHV_PARAM2=0		;不能被攻击（无敌）
BHV_PARAM3=35000		;离开出生地的距离大于此值时，放弃追赶敌人
BHV_PARAM4=5000		;扫描敌人的最大距离
BHV_PARAM5=8000		;扫描队友的最大距离
BHV_PARAM6=2000 ;!!!该项配置已经失效如果当前的移动目标和敌人的位置之间的距离大于此数值,则需要重新设定移动目标
BHV_PARAM7=1 		;是否可以回到原始状态，比如回血，清除buff
BHV_PARAM8=1		;是否会还击

[BHV6]
DESC=不主动攻击，不会随机移动，可以攻击，会还击
BHV_PARAM0=-1		;!!!-1非主动攻击， 其他数值无效，即扫描敌人的时间不可以进行配置
BHV_PARAM1=-1		;随机移动的时间间隔，如果是-1，则不会随机移动
BHV_PARAM2=0		;不能被攻击（无敌）
BHV_PARAM3=35000		;离开出生地的距离大于此值时，放弃追赶敌人
BHV_PARAM4=5000		;扫描敌人的最大距离
BHV_PARAM5=8000		;扫描队友的最大距离
BHV_PARAM6=2000 ;!!!该项配置已经失效如果当前的移动目标和敌人的位置之间的距离大于此数值,则需要重新设定移动目标
BHV_PARAM7=1 		;是否可以回到原始状态，比如回血，清除buff
BHV_PARAM8=1		;是否会还击


[BHV7]
DESC=不主动攻击，不会随机移动，可以攻击，不会还击
BHV_PARAM0=-1		;!!!-1非主动攻击， 其他数值无效，即扫描敌人的时间不可以进行配置
BHV_PARAM1=-1		;随机移动的时间间隔，如果是-1，则不会随机移动
BHV_PARAM2=0		;不能被攻击（无敌）
BHV_PARAM3=35000		;离开出生地的距离大于此值时，放弃追赶敌人
BHV_PARAM4=5000		;扫描敌人的最大距离
BHV_PARAM5=10000		;扫描队友的最大距离
BHV_PARAM6=2000 ;!!!该项配置已经失效如果当前的移动目标和敌人的位置之间的距离大于此数值,则需要重新设定移动目标
BHV_PARAM7=1 		;是否可以回到原始状态，比如回血，清除buff
BHV_PARAM8=0		;是否会还击

[BHV8]
DESC=不主动攻击，会随机移动，可以攻击，不会还击
BHV_PARAM0=-1		;!!!-1非主动攻击， 其他数值无效，即扫描敌人的时间不可以进行配置
BHV_PARAM1=10000		;随机移动的时间间隔，如果是-1，则不会随机移动
BHV_PARAM2=0		;不能被攻击（无敌）
BHV_PARAM3=35000		;离开出生地的距离大于此值时，放弃追赶敌人
BHV_PARAM4=5000		;扫描敌人的最大距离
BHV_PARAM5=8000		;扫描队友的最大距离
BHV_PARAM6=2000 ;!!!该项配置已经失效如果当前的移动目标和敌人的位置之间的距离大于此数值,则需要重新设定移动目标
BHV_PARAM7=1 		;是否可以回到原始状态，比如回血，清除buff
BHV_PARAM8=0		;是否会还击

[BHV9]
DESC=主动攻击，不会随机移动，可以攻击，会还击，全地图追击，中扫描范围(副本专用)
BHV_PARAM0=1000 ;!!!-1非主动攻击， 其他数值无效，即扫描敌人的时间不可以进行配置
BHV_PARAM1=-1		;随机移动的时间间隔，如果是-1，则不会随机移动
BHV_PARAM2=0		;不能被攻击（无敌）
BHV_PARAM3=1000000	;离开出生地的距离大于此值时，放弃追赶敌人
BHV_PARAM4=8000		;扫描敌人的最大距离
BHV_PARAM5=8000		;扫描队友的最大距离
BHV_PARAM6=2000 ;!!!该项配置已经失效如果当前的移动目标和敌人的位置之间的距离大于此数值,则需要重新设定移动目标
BHV_PARAM7=1 		;是否可以回到原始状态，比如回血，清除buff
BHV_PARAM8=1		;是否会还击

[BHV10]
DESC=主动，不会随机，可以攻击，会还击90000
BHV_PARAM0=1000 ;!!!-1非主动攻击， 其他数值无效，即扫描敌人的时间不可以进行配置
BHV_PARAM1=-1		;随机移动的时间间隔，如果是-1，则不会随机移动
BHV_PARAM2=0		;不能被攻击（无敌）
BHV_PARAM3=2000	        ;离开出生地的距离大于此值时，放弃追赶敌人
BHV_PARAM4=5000		;扫描敌人的最大距离
BHV_PARAM5=-1		;扫描队友的最大距离
BHV_PARAM6=2000 ;!!!该项配置已经失效如果当前的移动目标和敌人的位置之间的距离大于此数值,则需要重新设定移动目标
BHV_PARAM7=1 		;是否可以回到原始状态，比如回血，清除buff
BHV_PARAM8=1		;是否会还击

[BHV11]
DESC=主动，不会随机，可以攻击，会还击50000
BHV_PARAM0=1000 ;!!!-1非主动攻击， 其他数值无效，即扫描敌人的时间不可以进行配置
BHV_PARAM1=-1		;随机移动的时间间隔，如果是-1，则不会随机移动
BHV_PARAM2=0		;不能被攻击（无敌）
BHV_PARAM3=2000	        ;离开出生地的距离大于此值时，放弃追赶敌人
BHV_PARAM4=5000		;扫描敌人的最大距离
BHV_PARAM5=-1		;扫描队友的最大距离
BHV_PARAM6=2000 ;!!!该项配置已经失效如果当前的移动目标和敌人的位置之间的距离大于此数值,则需要重新设定移动目标
BHV_PARAM7=1 		;是否可以回到原始状态，比如回血，清除buff
BHV_PARAM8=1		;是否会还击

[BHV12]
DESC=主动，不会随机，可以攻击，会还击10000
BHV_PARAM0=1000 ;!!!-1非主动攻击， 其他数值无效，即扫描敌人的时间不可以进行配置
BHV_PARAM1=-1		;随机移动的时间间隔，如果是-1，则不会随机移动
BHV_PARAM2=0		;不能被攻击（无敌）
BHV_PARAM3=2000	        ;离开出生地的距离大于此值时，放弃追赶敌人
BHV_PARAM4=5000		;扫描敌人的最大距离
BHV_PARAM5=-1		;扫描队友的最大距离
BHV_PARAM6=2000 ;!!!该项配置已经失效如果当前的移动目标和敌人的位置之间的距离大于此数值,则需要重新设定移动目标
BHV_PARAM7=1 		;是否可以回到原始状态，比如回血，清除buff
BHV_PARAM8=1		;是否会还击

[BHV13]
DESC=主动，不会随机，可以攻击，会还击5000
BHV_PARAM0=1000 ;!!!-1非主动攻击， 其他数值无效，即扫描敌人的时间不可以进行配置
BHV_PARAM1=-1		;随机移动的时间间隔，如果是-1，则不会随机移动
BHV_PARAM2=0		;不能被攻击（无敌）
BHV_PARAM3=2000	        ;离开出生地的距离大于此值时，放弃追赶敌人
BHV_PARAM4=5000		;扫描敌人的最大距离
BHV_PARAM5=-1		;扫描队友的最大距离
BHV_PARAM6=2000 ;!!!该项配置已经失效如果当前的移动目标和敌人的位置之间的距离大于此数值,则需要重新设定移动目标
BHV_PARAM7=1 		;是否可以回到原始状态，比如回血，清除buff
BHV_PARAM8=1		;是否会还击

[BHV14]
DESC=主动攻击，不会随机移动，可以攻击，会还击，全地图追击,小扫描范围(副本专用)
BHV_PARAM0=1000 ;!!!-1非主动攻击， 其他数值无效，即扫描敌人的时间不可以进行配置
BHV_PARAM1=-1		;随机移动的时间间隔，如果是-1，则不会随机移动
BHV_PARAM2=0		;不能被攻击（无敌）
BHV_PARAM3=1000000	;离开出生地的距离大于此值时，放弃追赶敌人
BHV_PARAM4=5000		;扫描敌人的最大距离
BHV_PARAM5=8000		;扫描队友的最大距离
BHV_PARAM6=2000 ;!!!该项配置已经失效如果当前的移动目标和敌人的位置之间的距离大于此数值,则需要重新设定移动目标
BHV_PARAM7=1 		;是否可以回到原始状态，比如回血，清除buff
BHV_PARAM8=1		;是否会还击

[BHV15]
DESC=不主动攻击，不会随机移动，可以攻击，会还击，全地图追击,大扫描范围(副本专用)
BHV_PARAM0=-1		;!!!-1非主动攻击， 其他数值无效，即扫描敌人的时间不可以进行配置
BHV_PARAM1=-1		;随机移动的时间间隔，如果是-1，则不会随机移动
BHV_PARAM2=0		;不能被攻击（无敌）
BHV_PARAM3=1000000	;离开出生地的距离大于此值时，放弃追赶敌人
BHV_PARAM4=5000		;扫描敌人的最大距离
BHV_PARAM5=8000		;扫描队友的最大距离
BHV_PARAM6=2000 ;!!!该项配置已经失效如果当前的移动目标和敌人的位置之间的距离大于此数值,则需要重新设定移动目标
BHV_PARAM7=1 		;是否可以回到原始状态，比如回血，清除buff
BHV_PARAM8=1		;是否会还击

[BHV16]
DESC=主动攻击，会随机移动，可以攻击（巡逻），会还击
BHV_PARAM0=1000 ;!!!-1非主动攻击， 其他数值无效，即扫描敌人的时间不可以进行配置
BHV_PARAM1=15000		;随机移动的时间间隔，如果是-1，则不会随机移动
BHV_PARAM2=0		;不能被攻击（无敌）
BHV_PARAM3=17000		;离开出生地的距离大于此值时，放弃追赶敌人
BHV_PARAM4=5000		;扫描敌人的最大距离
BHV_PARAM5=8000		;扫描队友的最大距离
BHV_PARAM6=2000 ;!!!该项配置已经失效如果当前的移动目标和敌人的位置之间的距离大于此数值,则需要重新设定移动目标
BHV_PARAM7=1 		;是否可以回到原始状态，比如回血，清除buff
BHV_PARAM8=1		;是否会还击

[BHV17]
DESC=不主动攻击，会随机移动，可以攻击，会还击
BHV_PARAM0=-1		;!!!-1非主动攻击， 其他数值无效，即扫描敌人的时间不可以进行配置
BHV_PARAM1=12000		;随机移动的时间间隔，如果是-1，则不会随机移动
BHV_PARAM2=0		;不能被攻击（无敌）
BHV_PARAM3=30000		;离开出生地的距离大于此值时，放弃追赶敌人
BHV_PARAM4=5000		;扫描敌人的最大距离
BHV_PARAM5=8000		;扫描队友的最大距离
BHV_PARAM6=2000 ;!!!该项配置已经失效如果当前的移动目标和敌人的位置之间的距离大于此数值,则需要重新设定移动目标
BHV_PARAM7=1 		;是否可以回到原始状态，比如回血，清除buff
BHV_PARAM8=1		;是否会还击

[BHV18]
DESC=主动攻击，不会随机移动，可以攻击，会还击
BHV_PARAM0=1000 ;!!!-1非主动攻击， 其他数值无效，即扫描敌人的时间不可以进行配置
BHV_PARAM1=-1		;随机移动的时间间隔，如果是-1，则不会随机移动
BHV_PARAM2=0		;不能被攻击（无敌）
BHV_PARAM3=35000		;离开出生地的距离大于此值时，放弃追赶敌人
BHV_PARAM4=8000		;扫描敌人的最大距离
BHV_PARAM5=20000          ;扫描队友的最大距离
BHV_PARAM6=2000 ;!!!该项配置已经失效如果当前的移动目标和敌人的位置之间的距离大于此数值,则需要重新设定移动目标
BHV_PARAM7=1 		;是否可以回到原始状态，比如回血，清除buff
BHV_PARAM8=1		;是否会还击


[BHV19]
DESC=主动攻击，不会随机移动，可以攻击，会还击
BHV_PARAM0=1000 ;!!!-1非主动攻击， 其他数值无效，即扫描敌人的时间不可以进行配置
BHV_PARAM1=-1		;随机移动的时间间隔，如果是-1，则不会随机移动
BHV_PARAM2=0		;不能被攻击（无敌）
BHV_PARAM3=35000		;离开出生地的距离大于此值时，放弃追赶敌人
BHV_PARAM4=20000		;扫描敌人的最大距离
BHV_PARAM5=20000          ;扫描队友的最大距离
BHV_PARAM6=2000 ;!!!该项配置已经失效如果当前的移动目标和敌人的位置之间的距离大于此数值,则需要重新设定移动目标
BHV_PARAM7=1 		;是否可以回到原始状态，比如回血，清除buff
BHV_PARAM8=1		;是否会还击

[BHV20]
DESC=主动攻击，不会随机移动，可以攻击，会还击
BHV_PARAM0=1000 ;!!!-1非主动攻击， 其他数值无效，即扫描敌人的时间不可以进行配置
BHV_PARAM1=-1		;随机移动的时间间隔，如果是-1，则不会随机移动
BHV_PARAM2=0		;不能被攻击（无敌）
BHV_PARAM3=35000		;离开出生地的距离大于此值时，放弃追赶敌人
BHV_PARAM4=21000		;扫描敌人的最大距离
BHV_PARAM5=8000		;扫描队友的最大距离
BHV_PARAM6=2000 ;!!!该项配置已经失效如果当前的移动目标和敌人的位置之间的距离大于此数值,则需要重新设定移动目标
BHV_PARAM7=1 		;是否可以回到原始状态，比如回血，清除buff
BHV_PARAM8=1		;是否会还击

[BHV21]
DESC=主动攻击，会随机移动，可以攻击（巡逻），会还击
BHV_PARAM0=1000 ;!!!-1非主动攻击， 其他数值无效，即扫描敌人的时间不可以进行配置
BHV_PARAM1=15000		;随机移动的时间间隔，如果是-1，则不会随机移动
BHV_PARAM2=0		;不能被攻击（无敌）
BHV_PARAM3=30000		;离开出生地的距离大于此值时，放弃追赶敌人
BHV_PARAM4=18000		;扫描敌人的最大距离
BHV_PARAM5=8000		;扫描队友的最大距离
BHV_PARAM6=2000 ;!!!该项配置已经失效如果当前的移动目标和敌人的位置之间的距离大于此数值,则需要重新设定移动目标
BHV_PARAM7=1 		;是否可以回到原始状态，比如回血，清除buff
BHV_PARAM8=1		;是否会还击

[BHV22]
DESC=主动攻击，不会随机移动，可以攻击（不巡逻），会还击，不追击（战场专用，箭塔等不动类型）
BHV_PARAM0=1000 ;!!!-1非主动攻击， 其他数值无效，即扫描敌人的时间不可以进行配置
BHV_PARAM1=-1		;随机移动的时间间隔，如果是-1，则不会随机移动
BHV_PARAM2=0		;不能被攻击（无敌）
BHV_PARAM3=0		;离开出生地的距离大于此值时，放弃追赶敌人
BHV_PARAM4=21000		;扫描敌人的最大距离
BHV_PARAM5=8000		;扫描队友的最大距离
BHV_PARAM6=2000 ;!!!该项配置已经失效如果当前的移动目标和敌人的位置之间的距离大于此数值,则需要重新设定移动目标
BHV_PARAM7=0 		;是否可以回到原始状态，比如回血，清除buff
BHV_PARAM8=1		;是否会还击

[BHV23]
DESC=主动攻击，不会随机移动，可以攻击，会还击
BHV_PARAM0=1000 ;!!!-1非主动攻击， 其他数值无效，即扫描敌人的时间不可以进行配置
BHV_PARAM1=-1		;随机移动的时间间隔，如果是-1，则不会随机移动
BHV_PARAM2=0		;不能被攻击（无敌）
BHV_PARAM3=17000		;离开出生地的距离大于此值时，放弃追赶敌人
BHV_PARAM4=17000		;扫描敌人的最大距离
BHV_PARAM5=8000		;扫描队友的最大距离
BHV_PARAM6=2000 ;!!!该项配置已经失效如果当前的移动目标和敌人的位置之间的距离大于此数值,则需要重新设定移动目标
BHV_PARAM7=1 		;是否可以回到原始状态，比如回血，清除buff
BHV_PARAM8=1		;是否会还击

[BHV24]
DESC=主动攻击，会随机移动，可以攻击（巡逻），会还击
BHV_PARAM0=1000 ;!!!-1非主动攻击， 其他数值无效，即扫描敌人的时间不可以进行配置
BHV_PARAM1=15000		;随机移动的时间间隔，如果是-1，则不会随机移动
BHV_PARAM2=0		;不能被攻击（无敌）
BHV_PARAM3=30000		;离开出生地的距离大于此值时，放弃追赶敌人
BHV_PARAM4=18000		;扫描敌人的最大距离
BHV_PARAM5=8000		;扫描队友的最大距离
BHV_PARAM6=2000 ;!!!该项配置已经失效如果当前的移动目标和敌人的位置之间的距离大于此数值,则需要重新设定移动目标
BHV_PARAM7=0 		;是否可以回到原始状态，比如回血，清除buff
BHV_PARAM8=1		;是否会还击

[BHV25]
DESC=不主动攻击，会随机移动，可以攻击，会还击
BHV_PARAM0=1000		;!!!-1非主动攻击， 其他数值无效，即扫描敌人的时间不可以进行配置
BHV_PARAM1=-1		;随机移动的时间间隔，如果是-1，则不会随机移动
BHV_PARAM2=0		;不能被攻击（无敌）
BHV_PARAM3=30000		;离开出生地的距离大于此值时，放弃追赶敌人
BHV_PARAM4=18000		;扫描敌人的最大距离
BHV_PARAM5=8000		;扫描队友的最大距离
BHV_PARAM6=2000 ;!!!该项配置已经失效如果当前的移动目标和敌人的位置之间的距离大于此数值,则需要重新设定移动目标
BHV_PARAM7=0 		;是否可以回到原始状态，比如回血，清除buff
BHV_PARAM8=1		;是否会还击

[BHV26]
DESC=不主动攻击，会随机移动，可以攻击，会还击
BHV_PARAM0=-1 		;!!!-1非主动攻击， 其他数值无效，即扫描敌人的时间不可以进行配置
BHV_PARAM1=15000		;随机移动的时间间隔，如果是-1，则不会随机移动
BHV_PARAM2=0		;不能被攻击（无敌）
BHV_PARAM3=20000	;离开出生地的距离大于此值时，放弃追赶敌人	
BHV_PARAM4=5000	;扫描敌人的最大距离	
BHV_PARAM5=8000	;扫描队友的最大距离	
BHV_PARAM6=2000   ;!!!该项配置已经失效如果当前的移动目标和敌人的位置之间的距离大于此数值,则需要重新设定移动目标
BHV_PARAM7=1 	;是否可以回到原始状态，比如回血，清除buff	
BHV_PARAM8=1        ;是否会还击

[BHV27]
DESC=主动攻击，不会随机移动，可以攻击（巡逻），会还击
BHV_PARAM0=1000 ;!!!-1非主动攻击， 其他数值无效，即扫描敌人的时间不可以进行配置
BHV_PARAM1=-1		;随机移动的时间间隔，如果是-1，则不会随机移动
BHV_PARAM2=0		;不能被攻击（无敌）
BHV_PARAM3=30000		;离开出生地的距离大于此值时，放弃追赶敌人
BHV_PARAM4=18000		;扫描敌人的最大距离
BHV_PARAM5=8000		;扫描队友的最大距离
BHV_PARAM6=2000 ;!!!该项配置已经失效如果当前的移动目标和敌人的位置之间的距离大于此数值,则需要重新设定移动目标
BHV_PARAM7=0 		;是否可以回到原始状态，比如回血，清除buff
BHV_PARAM8=1		;是否会还击

[BHV28]
DESC=主动攻击，不会随机移动，可以攻击，会还击
BHV_PARAM0=1000 ;!!!-1非主动攻击， 其他数值无效，即扫描敌人的时间不可以进行配置
BHV_PARAM1=-1		;随机移动的时间间隔，如果是-1，则不会随机移动
BHV_PARAM2=0		;不能被攻击（无敌）
BHV_PARAM3=3500000		;离开出生地的距离大于此值时，放弃追赶敌人
BHV_PARAM4=500000		;扫描敌人的最大距离
BHV_PARAM5=20000          ;扫描队友的最大距离
BHV_PARAM6=2000 ;!!!该项配置已经失效如果当前的移动目标和敌人的位置之间的距离大于此数值,则需要重新设定移动目标
BHV_PARAM7=0 		;是否可以回到原始状态，比如回血，清除buff
BHV_PARAM8=1		;是否会还击

[BHV29]
DESC=主动攻击，会随机移动，可以攻击，会还击，全地图追击,大扫描范围(副本专用)
BHV_PARAM0=1000 ;!!!-1非主动攻击， 其他数值无效，即扫描敌人的时间不可以进行配置
BHV_PARAM1=5000		;随机移动的时间间隔，如果是-1，则不会随机移动
BHV_PARAM2=0		;不能被攻击（无敌）
BHV_PARAM3=1000000	;离开出生地的距离大于此值时，放弃追赶敌人
BHV_PARAM4=9000		;扫描敌人的最大距离
BHV_PARAM5=8000		;扫描队友的最大距离
BHV_PARAM6=2000 ;!!!该项配置已经失效如果当前的移动目标和敌人的位置之间的距离大于此数值,则需要重新设定移动目标
BHV_PARAM7=1 		;是否可以回到原始状态，比如回血，清除buff
BHV_PARAM8=1		;是否会还击

[BHV30]
DESC=不主动攻击，会随机移动，可以攻击，不会还击
BHV_PARAM0=-1		;!!!-1非主动攻击， 其他数值无效，即扫描敌人的时间不可以进行配置
BHV_PARAM1=500		;随机移动的时间间隔，如果是-1，则不会随机移动
BHV_PARAM2=0		;不能被攻击（无敌）
BHV_PARAM3=300		;离开出生地的距离大于此值时，放弃追赶敌人
BHV_PARAM4=100		;扫描敌人的最大距离
BHV_PARAM5=100		;扫描队友的最大距离
BHV_PARAM6=2000 ;!!!该项配置已经失效如果当前的移动目标和敌人的位置之间的距离大于此数值,则需要重新设定移动目标
BHV_PARAM7=1 		;是否可以回到原始状态，比如回血，清除buff
BHV_PARAM8=0		;是否会还击

[BHV31]
DESC=主动攻击，会随机移动，可以攻击，会还击，全地图追击,全地图扫描范围(副本专用)
BHV_PARAM0=1000 ;!!!-1非主动攻击， 其他数值无效，即扫描敌人的时间不可以进行配置
BHV_PARAM1=5000		;随机移动的时间间隔，如果是-1，则不会随机移动
BHV_PARAM2=0		;不能被攻击（无敌）
BHV_PARAM3=1000000	;离开出生地的距离大于此值时，放弃追赶敌人
BHV_PARAM4=1000000		;扫描敌人的最大距离
BHV_PARAM5=8000		;扫描队友的最大距离
BHV_PARAM6=2000 ;!!!该项配置已经失效如果当前的移动目标和敌人的位置之间的距离大于此数值,则需要重新设定移动目标
BHV_PARAM7=1 		;是否可以回到原始状态，比如回血，清除buff
BHV_PARAM8=1		;是否会还击